stages:
  - test

type-test:
  stage: test
  image: python3.9
  script:
    - pip install mypy
    - mypy src
  allow_failure: true

lint-test:
  stage: test
  image: python3.9
  script:
    - pip install flake8
    - flake8
  allow_failure: true