version: '3.9'

services:
  pet-store-flask:
    container_name: python-flask
    image: python-flask
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:admin@db:5432/postgres
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
